- name: configure cart 
  hosts: cart
  become: yes
  tasks:
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf: 
     name: nodejs
     state: present
  
  - name: create system user
    ansible.builtin.user:
     name: roboshop
     home: /app
     system: yes
     shell: /sbin/nologin
     comment: roboshop system user

  - name: delete app directory
    ansible.builtin.file:
     path: /app
     state: absent
  
  - name: create app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: delete cart zip file
    ansible.builtin.file:
     path: /tmp/cart.zip
     state: absent
  
  - name: download the application zip file
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
     dest: /tmp/cart.zip

  - name: unzip cart fil
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes
  
  - name: install nodejs dependencies
    community.general.npm:
     path: /app
  
  - name: copy cart system services
    ansible.builtin.template: 
     src: cart.service
     dest: /etc/systemd/system/cart.service

  - name: reload the daemon
    ansible.builtin.systemd_service:
     daemon_reload: true
  
  - name: enable and start cart
    ansible.builtin.service:
     name: cart
     state: restarted
     enabled: yes