- name: configure catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present
  
  - name: create system user
    ansible.builtin.user:
     name: roboshop
     system: true
     home: /app
     shell: /sbin/nologin
     comment: "Roboshop system user"
     
  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: Download application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
     dest: /tmp/catalogue.zip
  
  - name: unzip the application
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes    #catalogue is the remote server
  
  - name: install npm dependencies
    community.general.npm:
     path: /app

  - name: copy systemctl services
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
    
  - name: install mongodb client
    ansible.builtin.dnf:
     name: mongodb-mongosh
     state: present
  
  - name: check schema loaded or not
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
  
  - name: print the output
    ansible.builtin.debug:
     msg: "{{ catalogue_output }}"
  
  - name: load mongodb master data
    ansible.builtin.shell: mongosh --host ""{{ MONGODB_HOST }} </app/db/master-data.js
    when: catalogue_output.stdout | int < 0