- name: configure frontend server
  hosts: frontend
  become: yes
  tasks: 
  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y
  - name: install nginx
    ansible.builtin.dnf: 
     name: nginx
     state: present

  - name: enable and start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes

  - name: remove content from file
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent
  
  - name: Download application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
     dest: /tmp/frontend.zip
  
  - name: unzip the application
    ansible.builtin.unarchive:
     src: /tmp/frontend.zip
     dest: /usr/share/nginx/html 
     remote_src: yes

  - name: copy systemctl  nginx services
    ansible.builtin.template:
     src: nginx.conf
     dest: /etc/nginx/nginx.conf

  - name: restart the nginx
    ansible.builtin.service:
     name: nginx
     state: restarted
  
   
     