- name: create aws ec2-instances and route53 records
  hosts: all    #so we dont need to use inventory file: -i localhost,
  connection: local
  vars:
   sg_id: sg-0e0f9f37ba6f57a67
   ami_id: ami-0220d79f3f480ecf5
   env: dev
   instances:
    - mongodb
    - catalogue
  tasks: 
  - name: create ec2-instances
    amazon.aws.ec2_instance:
     instance_type: "t3.micro"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     name: "{{ item }}-{{ env }}"
     tags:
      Project: roboshop
      Component: "{{ item }}"
      Environment: "{{ env }}"
      Name: "{{ item }}-{{ env }}"
    loop: "{{  instances }}"
    register: ec2_output

  - name: print the output of ec2
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"

  



