- name: configure shipping service
  hosts: shipping
  become: yes
  tasks: 
  - name: install maven and mysql
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: present
    loop:
     - maven
     - mysql

  - name: create system user
    ansible.builtin.user:
     name: roboshop
     system: true
     home: /app
     shell: /sbin/nologin
     comment: "Roboshop system user"
  
  - name: delete app directory
    ansible.builtin.file:
     path: /app
     state: absent
     
  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: delete shipping zip file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: Download application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
     dest: /tmp/shipping.zip
  
  - name: unzip the application
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app
     remote_src: yes    #shipping is the remote server
  
  - name: install dependencies
    ansible.builtin.command: mvn clean package 
    args:
      chdir: /app

  - name: install dependecies
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args: 
       chdir: /app

  - name: create systemctl service
    ansible.builtin.template:
     src: shipping.service
     dest: /etc/systemd/system/shipping.service

  - name: daemon-reload
    ansible.bulitin.systemd_service:
     state: reload

  - name: import shipping data 
    community.mysql.mysql_db:
     state: import
     name: all
     login_host: "{{ MYSQL_HOST }}"
     login_user: root
     login_password: RoboShop@1
     target: "{{ item }}"
    loop:
     - /app/db/schema.sql
     - /app/db/app-user.sql 
     - /app/db/master-data.sql

  - name: enable and start the shiiping service
    ansible.builtin.service:
     name: shipping
     state: restarted
     enabled: yes